###
GET http://127.0.0.1:3000/servo
Content-Type: application/json

###
GET http://127.0.0.1:3000/?query=1
Content-Type: application/json
X-Request-Id: e07b71fa-ac43-4c48-9928-1d0f6f1b8016

###
POST http://127.0.0.1:3000/servo
Content-Type: application/json

{"name": "hhh",
"type": 1,
  "description": "asfdsafa"
}
