###
POST http://127.0.0.1:3000/servo
Content-Type: application/json

{
  "value": "content"
}

###
GET http://127.0.0.1:3000/servo
Content-Type: application/json

###
GET http://127.0.0.1:3000/
Content-Type: application/json
x-requestId 1sfadsfasf

###
POST http://127.0.0.1:3000/servo
Content-Type: application/json

{"name": "hhh",
"type": 1,
  "description": "asfdsafa"
}
